sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: " DOCKER-REACT"
  env: "DockerReact-env" 
  bucket_name: "elasticbeanstalk-us-east-1-696585142095"
  bucket_path: "DOCKER-REACT"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
   
